config/routes.rb
Rails.application.routes.draw do
  resources :search, only: %i[index]
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredient_recipes
  has_many :recipes, through: :ingredient_recipes

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredient_recipes
  has_many :ingredients, through: :ingredient_recipes

  validates :title, presence: true
  validates :cook_time, presence: true
  validates :prep_time, presence: true
  validates :ratings, presence: true
  validates :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @recipes = Recipes::FindRecipesWithIngredients.new(
      search_params
    ).call
    rescue ActionController::ParameterMissing
      redirect_to root_path
  end

  def search_params
    params.require(:ingredients)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= render 'shared/recipe_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinner Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<% splitted_params = params[:ingredients].split(',') %>

<%= render 'shared/recipe_form' %>

<% if @recipes.present? %>
  <div class="grid grid-cols-1 place-items-center">
    <p class="text-green-700 mb-6">Found <%= @recipes.size %> recipes matching your search.</p>
  </div>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4 px-4">
    <% @recipes.each do |recipe| %>
      <div class="rounded-lg shadow-md overflow-hidden">
        <img src="<%= recipe.image_url %>" class="w-full h-40 object-cover" alt="<%= recipe.title %>">
        <div class="p-4">
          <h5 class="text-lg font-semibold mb-2"><%= recipe.title %></h5>
          <p class="text-gray-700 mb-1">
            Rating: <%= recipe.ratings %> stars
          </p>
          <p class="text-gray-700">
            <ul class="list-disc pl-4">
              <% recipe.ingredients.each do |ingredient| %>
                <% highlight_ingredient = splitted_params.any? { |search_ingredient| ingredient.name.include?(search_ingredient) } %>
                <li class="text-gray-700 <%='text-green-500 font-bold' if highlight_ingredient %>">
                  <%= ingredient.name %>
                </li>
              <% end %>
            </ul>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="grid grid-cols-1 place-items-center ">
    <p class="text-green-700 mb-4 justify-center">No recipes found for search term: <span class="text-red-700 mt-0"><%= params[:ingredients] %></span></p>
  </div>
<% end %>

app/views/shared/_recipe_form.html.erb
<div class="container mx-auto mt-5 mb-10 px-4 flex justify-center">
  <div class="w-full max-w-md">
    <h1 class="text-3xl font-bold mb-3">Search Recipes</h1>
    <%= form_tag(search_index_path, method: "get", class: "flex flex-col gap-2") do %>
        <%= label_tag :ingredients, "Ingredients (comma separated)", class: "text-base font-medium" %>
        <%= text_field_tag :ingredients, params[:ingredients], class: "border rounded-md px-3 py-2 focus:outline-none focus:ring-1 focus:ring-blue-500", id: "ingredients", placeholder: "e.g., egg, flour, baking powder, milk", required: true %>
      <%= submit_tag "Search Recipes", class: "bg-blue-500 text-white rounded-md py-2 px-4 hover:bg-blue-700" %>
    <% end %>
    <div id="results"></div>
  </div>
</div>